Small Windows fix.
Tried it on Windows, but it failed with:
```
  File "F:\MingW32\src\TUI\Slang\src\fish-tank.py", line 37, in init_curses_color
    curses.init_pair(i, i, -1)
_curses.error: init_pair() returned ERR
```

No idea really what's the cause. So I this patch gives black & white colours for Windows.